### PR TITLE
Add more languages

### PR DESCRIPTION
**Pull request by MathiasDPX**
I use [LocaleAPI](https://github.com/MathiasDPX/LocaleAPI),

<details>
<summary>Screenshots</summary>

Game in English
game_in_english

Game in French
game_in_french

Game in pirate (not supported)
game_in_pirate
</details>

Servers owners can however translate plugins to their lang by adding a yml file in plugins/jLevels/locales

### CODE REVIEW

**Comment by JoJjjo174** [comment]
Thanks! I'll have a look at it tomorrow :D

**Comment by JoJjjo174** [comment]
Hi, localeapi changes the language based on the player's ip right? If so, is it possible so you can disable this feature in the config? I could imagine some server admins not wanting this because they want one uniform language on their server for all players.

**Comment by MathiasDPX** [comment]
> Hi, localeapi changes the language based on the player's ip right? If so, is it possible so you can disable this feature in the config? I could imagine some server admins not wanting this because they want one uniform language on their server for all players.

It's based on the player locale, not player ip but yes you can disable it

**Comment by MathiasDPX** [comment]
Done!
I added `uniform_language` to config

**Comment by JoJjjo174** [comment]
Awesome!

**Pull request merged**
